### ISSUE TITLE
Can't reformat tag.

### ISSUE THREAD

**Issue by Notunderscore** [HiddenRamblings/TagMo#217]
Hi, I wanted to format the tag that I formatted as an amiibo so I can use it for another purpose, but whenever I go into the erase tag option on my phone, it is unable to format the tag. Is there any way of doing it ?

**Comment by xcession** [comment]
Unfortunately, no. The tag is only write "once".

**Comment by burndive** [comment]
Technically, you can write more than once, since amiibo tags can store and modify data.  What you can only do once is format, in this case, formatting establishes the identity of the tag as a particular amiibo.

So, if you make a tag into a Mario amiibo, you can modify Mario's game data, but you can't make it not Mario.
