### ISSUE TITLE
Cant set bank count to 1

### ISSUE THREAD

**Issue by BlackRabbit22** [HiddenRamblings/TagMo#306]
Can't set amiibo bank count to 1, says "Active beyond new count".

Also, if the current bank count is 1, and you click on the current used bank slot, a crash occurs.

**Comment by AbandonedCart** [comment]
I'm not entirely sure why the error is popping up, but I made some temporary changes to prevent it until I can figure that out.

Extended explanation: 

The active bank is a zero-based index (0 - 199) and the bank count is a length / size (1 - 200). A list has a zero-based position, but all the pickers only return the value displayed, which is one of 1 - 200 (because 0 is confusing here).

The active bank will always be one less than the bank count, since "position + 1 = value". In theory, that means an active bank equal to the bank count is actually one over the bank count, which is how the code was written. For some odd reason, though, that is what is causing the bug.

As a temporary solution (until I figure out what is getting mixed up), it is set to make sure the active slot is actually two more than the bank count before preventing action. This may end up shifting the issue to the top end, but hopefully that gets resolved by the simple fact that it's impossible to write beyond the end of the banks.
