### ISSUE TITLE
Purple text and view missing

### ISSUE THREAD

**Issue by ishtangli** [HiddenRamblings/TagMo#336]
Some Amiibos have a purple text.. and it moves when you refresh. What are the purple ones?

![Screenshot_20211108-115953](https://user-images.githubusercontent.com/17796839/140682599-65179bd9-7221-43c9-bb47-b15b4bb0e31a.jpg)

Also, the count below shows i have missing amiibos  any way to see which they are?

**Comment by AbandonedCart** [comment]
Extended menu -> Content -> Show Missing

**Comment by ishtangli** [comment]
Tried it and it just says searching amiibo. Left it for a while too

**Comment by AbandonedCart** [comment]
Sounds like your loading time is just really slow. What device is it?

**Comment by ishtangli** [comment]
Oneplus 6T McLaren

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/commit/00c144c4af567c17c6714ef7452fcce9509ce31b should help, at least a little.

**Comment by AbandonedCart** [comment]
If you have the option to show missing enabled, the path is highlighted for ones you have as they appear. This was implemented before me, so I will have to look into it. 

I will also disable the search text with the option enabled, since even not finding files will still have results. It was set to display until files are found, but showing missing breaks the check.
