### ISSUE TITLE
I can't open app.

### ISSUE THREAD

**Issue by Entrotom** [HiddenRamblings/TagMo#377]
Hello. Whenever I try to open app, crashes happen and I can't use this app. I tried to download all version app. The olds can be opend but tag is not recognized, and new versions are crashed. I want to attach my crash log, but there's even no log in tagmo folder. My device is SAMSUNG GALAXY 10+. I really want to use this app and  need help. Thanks.

**Comment by AbandonedCart** [comment]
Without a log, there is no way of knowing why TagMo crashed.

https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/

**Comment by AbandonedCart** [comment]
Just to be sure, are you checking the "TagMo" folder in Download/TagMo or were you looking in Android/data/com.hiddenramblings.tagmo/files because the first one is where the log should write.

3afd8e76cc91d219d3549ac4a9ad703c6a55da02 adds a fallback to the second directory if writing to the first fails for some reason, but versions before that ONLY write to the Download folder.
