### ISSUE TITLE
Flask Support 

### ISSUE THREAD

**Issue by Ericzion1999** [HiddenRamblings/TagMo#405]
Hey it is planned to support the Flask  at some point?

**Comment by AbandonedCart** [comment]
![Screenshot_20220216-053451797](https://user-images.githubusercontent.com/1173913/154246990-1b46c974-dc14-42ca-a5f0-e89e4f740018.png)

**Comment by Ericzion1999** [comment]
That doesnt Work for me

**Comment by AbandonedCart** [comment]
The only stuff for Flask is labeled "Bluup Flask"

That is the only thing we could offer. Contacted the creator of the thing and he wanted to make it all about trying to sell the future of what he is considering making, not how to make what he already sold better.

**Comment by Ericzion1999** [comment]
Oh okay , thank you

**Comment by AbandonedCart** [comment]
You spoke to me. Ironically, you made all the same points. Never received any further info on the API, but I did get a whole lot of your thoughts on making a more affordable alternative.

Any hostility you feel is yours to drop. I am blunt. I asked if you wanted to be supported and got a bunch of back story about how you don't have the time. Maybe I see the world differently, but sending someone an API link seems like a lot less time spent than writing numerous lengthy posts explaining how you could.

**Comment by withgallantry** [comment]
Thanks for the clarity. I think I understand your point of view a more. I know what conversation you meant now, I wasn't aware at the time who you were in relation to TagMo. The answers I gave were answers I'd give to general users who might ask about native apps. I don't have time currently to build and maintain my own, other parts of the project would suffer. I also enjoy and am passionate about what I do and do go off on tangents hence the lengthy posts at times. It's what I like to do in my down time.

Here is the API doc for yourself or anyone that's interested. It will be updated in the coming weeks, the upload process will be changing to make it faster. If anyone is interested, I'll send them a Flask to develop against with no expectation that it will be implemented either. https://docs.google.com/document/d/1oc5FdTeeTUCSetNBA97S1RRqBeZalA8Gk9wvWmT4QAg

I feel this is resolved and was partly due to slight crossed wires on my end.

**Comment by AbandonedCart** [comment]
Thanks. I'll look at the API docs and see what I can get running. You can send a Flask or not. That is purely up to you. Being the only active member of TagMo (with push access) at the moment, it's a little easier to manage supporting new hardware. It sounds backwards, but more hands need more devices and then who gets what?

**Comment by withgallantry** [comment]
I know what you mean. Easier than stepping on each other toes.
I'm happy to send one. I'm just currently putting some together so will have more in about two weeks, I'll reach out when I do. I'll have updated the API doc around the uploading also by that point.

**Comment by AbandonedCart** [comment]
Cleaned up and reopened to be the "getting it supported" issue.

**Comment by DanTheMan827** [comment]
@withgallantry it might be worthwhile to also implement N2 emulation in the flask itself.

That way it would gain support in all sorts of apps for "free"

You can find some documentation of the various commands here:
https://wiki.yobi.be/index.php/N2_Elite

**Comment by AbandonedCart** [comment]
How many people have these things that can start testing?

**Comment by Ericzion1999** [comment]
I can Test it

**Comment by AbandonedCart** [comment]
@withgallantry Still the same API?

**Comment by AbandonedCart** [comment]
Looks like there wasn't quite enough in PayPal to order one on this batch. Maybe next time.

**Comment by Ericzion1999** [comment]
> How many people have these things that can start testing?

Is it possible, that i can Test it?

**Comment by Miss1sle** [comment]
I can test too

**Comment by AbandonedCart** [comment]
What does the hardware come up as in the Bluetooth device list?

**Comment by Ericzion1999** [comment]
> What does the hardware come up as in the Bluetooth device list?

![IMG_20220313_234015](https://user-images.githubusercontent.com/82835573/158082239-cd985e4d-bed6-4e4e-8148-ef478bb8e834.jpg)

**Comment by Ericzion1999** [comment]
The app doesnt find the flask

**Comment by AbandonedCart** [comment]
Unfortunately, I have no way to test any of the code locally. Being over two weeks without a response from the developer of the device, it looks like we cannot move forward on this at this time.

**Comment by AbandonedCart** [comment]
Testing is open to anyone. There are no hidden branches.
