### ISSUE TITLE
Recommendations for user experience optimization

### ISSUE THREAD

**Issue by lzcer** [HiddenRamblings/TagMo#482]
First of all, your work is great, but there are a few issues that slightly affect the experience, so here are a few suggestions for you to consider.

1. Every time you enter the app, you will re-scan all the bin files from the selected root directory. When the bin files are large, for example, I currently have more than 900 files, the re-scan will use 2-3s time, i think it would be better if I could cache bin's information instead of having to re-scan every time I enter the app.

2. For images pulled from the API web site, each render takes a file from the cloud and renders to the corresponding entry, which is a time consuming process, it would be nice if it could be cached locally with problem 1.

The above is my personal some humble opinion, if your current product already has the solution, but also trouble you to inform, if no solution, Hope can help you.

**Comment by AbandonedCart** [comment]
It sounds like the issue is not in the caching, but in the device. I currently have over 900 files and the initial load takes around 1 -2 seconds from a fresh launch. Subsequent launches are instantaneous. 

Caching the bin information would actually increase that load time exponentially, as you would now be reading a database in place of the files before cross-referencing the physical files. This would introduce a substantial amount of reliability concerns if the device could not filter changes, additions, and removals before presenting them as loaded files. Unlike displaying the name and size in a file manager, the app is displaying file data. If you run grep on 900 files, you can expect to be waiting minutes. Taking that into consideration, 3 seconds is hardly significant.

As for the images, they are cached. It is handled by Glide. If you are manually selecting the Sync option from the extended menu (three dots in the upper right), then it will reset the cache. Beyond that, the images should only ever load once and then subsequently load from your local cache. Again, this would be limited by the performance of the device.

This is not the first time someone has suggested something along these lines. Unfortunately, the recurring trend also appears to be doing so without having glanced at the source or investigating the suggestion to confirm it is viable.
