### ISSUE TITLE
Min API Level

### ISSUE THREAD

**Issue by North101** [HiddenRamblings/TagMo#67]
@HiddenRambler 

The min api level is set to level 14, however NfcAdapter.ACTION_ADAPTER_STATE_CHANGED requires a min api level of 18. Should we increase it? It seems like this would cause a crash on NFC enabled devices < Android ICS (non NFC enabled devices wouldn't get to that bit of the code).

Below is the current distribution of android versions. I think we can safely update it to at least 18 though preferably 19.
<img width="564" alt="screen shot 2017-08-04 at 16 21 36" src="https://user-images.githubusercontent.com/1031451/28975823-6e051b7c-7933-11e7-8185-528abcfed8f4.png">

**Comment by HiddenRambler** [comment]
When the app was first developed there were some users who explicitly asked for <4.4 android support, which is why I chose that api level.

ACTION_ADAPTER_STATE_CHANGED is used solely to warn the user about Nfc enabled state. We could wrap the code that uses it in an exception handler and ignore any exceptions without affecting other functionality.

I will however ask a question on gbatemp asking if anyone is using <4.3 so we can decide what to do.

**Comment by North101** [comment]
Ok, thats understandable. We can probably keep the API level as is then. Should probably add an API check to that then. I havent had a proper look at how the NFC functionality works so I was unsure whether it required level 18 or not
