### ISSUE TITLE
No Play Store release?

### ISSUE THREAD

**Issue by r2DoesInc** [HiddenRamblings/TagMo#78]
Just wondering why there hasnt been a play store release?

**Comment by Bombastisch** [comment]
The app is not finished yet, so a release would have no benefits.

Secondly I don't think Nintendo would like it and so Google won't release it.

**Comment by r2DoesInc** [comment]
Finished is a relative term :P 
I dont think Nintendo would be be a problem other than using Nintendo or Amiibo in the name.

**Comment by Bombastisch** [comment]
But this app is all about Amiibos and how to make your own ones! I guesss Nintendo isn't a fan of this project as we are! xD

**Comment by Bombastisch** [comment]
I guess we can close. I don't see any reason __yet__ to ask Google to release it on their app store. But it's the desicion of the devs. Maybe on day it will be available on Google Play. (The app I am using doesn't allow me close the issue, because of third party restrictions of Github) Please close it by yourself. 

Thank you :)
